version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: nestjs-url-shortener-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: nestjs-url-shortener-redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-url-shortener-app
    ports:
      - '3001:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
